# Generated by Django 5.2 on 2025-04-18 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("street", models.CharField(max_length=255, verbose_name="Street")),
                (
                    "postal_code",
                    models.CharField(max_length=8, verbose_name="Postal code"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("country", models.CharField(max_length=255, verbose_name="Country")),
            ],
            options={
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
                "ordering": ["-created_at"],
            },
        ),
    ]
