# Generated by Django 6.0.5 on 2026-06-03 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donation_amount_alter_donation_donor"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="donation_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Donation date",
            ),
        ),
    ]
