# Generated by Django 5.2.3 on 2025-06-14 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0002_alter_donation_amount_alter_donation_donor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.CharField(max_length=255, verbose_name="Pretix Order ID"),
                ),
                ("position_id", models.IntegerField(verbose_name="Pretix Position ID")),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretix_orders",
                        to="donations.donation",
                        verbose_name="Donation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pretix Order",
                "verbose_name_plural": "Pretix Orders",
                "ordering": ["created_at"],
                "default_permissions": (),
                "unique_together": {("order_id", "position_id")},
            },
        ),
    ]
