# Generated by Django 5.2.3 on 2025-06-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dontrack_pretix", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "default_permissions": (),
                "ordering": ["created_at"],
                "verbose_name": "Pretix order",
                "verbose_name_plural": "Pretix orders",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=255, verbose_name="Pretix order id"),
        ),
        migrations.AlterField(
            model_name="order",
            name="position_id",
            field=models.IntegerField(verbose_name="Pretix position id"),
        ),
    ]
