# Generated by Django 6.0.5 on 2026-06-03 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dontrack_pretix", "0002_alter_order_options_alter_order_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Pretix order date"
            ),
            preserve_default=False,
        ),
    ]
